### ISSUE TITLE
Support Minima 2.2.1

### ISSUE THREAD

**Issue by matteeyah** [github/pages-gem#520] opened 2018-01-26 14:18 UTC
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (run `bundle update github-pages`)

## Before suggesting a Jekyll plugin, please make sure the plugin is

- [x] useful for a vast majority of users
- [x] available as a gem
- [ ] covered with a test suite
- [x] actively maintained

### This issue affects

- [x] The site generated by GitHub Pages
- [x] Building sites locally

*The GitHub Pages Gem is intended to help users replicate the GitHub Pages build environment locally. If your issue affects both the hosted version and the version previewed locally, you may be better suited reporting [seeking support in other forums](https://github.com/github/pages-gem/blob/master/.github/CONTRIBUTING.md#where-to-get-help-or-report-an-issue).*

### Summary

Minima 2.2.0 got released 4 days ago - https://github.com/jekyll/minima/issues/170#issuecomment-359567443 - https://rubygems.org/gems/minima

It has no additional dependencies and can be a drop in a replacement for Minima 2.1, which is currently used by github-pages.

**Comment by malreynolds** [comment] 2018-01-28 13:39
minima now has a new a new version, [2.2.1](https://github.com/jekyll/minima/releases/tag/v2.2.1), which introduces a small fix with backwards compatibility. Could you update your PR to reflect that?

**Comment by matteeyah** [comment] 2018-01-28 21:43
@malreynolds I pushed another commit to bump it to 2.2.1. I also updated the PR and the issue title. Thanks!

**Comment by matteeyah** [comment] 2018-02-06 17:38
Bumped it to 2.3.0.

**Comment by DirtyF** [comment] 2018-03-14 18:41
Duplicate of #539 #521

**Closed** 2018-03-16 19:57 UTC
