### ISSUE TITLE
Empty string for baseurl treated as baseurl: nil

### ISSUE THREAD

**Issue by cameronmcefee** [github/pages-gem#359] opened 2016-11-28 19:35 UTC
*I'm not quite sure if this is the correct place for this. Technically I think `baseurl` handling is part of jekyll/jekyll, but I believe GitHub Pages is setting the default that is causing the problem. This could  also possibly be considered a dupe of #350. Please redirect me if need-be.*

### This issue affects

- [x] The site generated by GitHub Pages
- [ ] Building sites locally

### What did you do (e.g., steps to reproduce)

We don't have a CNAME file in the repo (handled instead by the load balancer, I'm told).

In the config:

```
url: 'https://blog.sentry.io'
baseurl: ''
```

### What did you expect to happen?

`{{ '/test.html' | absolute_url }}` should be "https://blog.sentry.io/test.html"

### What happened instead?

`{{ '/test.html' | absolute_url }}` gets "https://blog.sentry.io/blog/test.html" 

### Additional information

when `baseurl: 'foo'` it gets "https://blog.sentry.io/foo/test.html"

I've been digging in this and the Jekyll codebase and can't find the source (my ruby is a little rusty). From that I can tell though, it seems like rather than `baseurl` being checked as nil, it's being checked as blank, causing `''` to fail despite being an intentional value (and recommended in the docs).

**Comment by mattrobenolt** [comment] 2016-11-28 19:46
To add in the concrete details here:

We use our own load balancers to terminate for TLS. So we have `http://blog.sentry.io` routing through us. Here's the relevant nginx snippets:

```nginx
upstream github {
  server getsentry.github.io;
}

server {
  listen 443 ssl;
  server_name blog.sentry.io;

  location / {
    proxy_buffering        off;
    proxy_http_version     1.1;
    proxy_set_header       Host getsentry.github.io;

    proxy_pass  http://github/blog/;
  }
}
```

So we're proxying all requests to us, and then also forwarding along to `/blog/` to mask these as the CNAME would.

**Comment by parkr** [comment] 2016-11-28 19:52
Hey, @cameronmcefee! The [code you're looking for is in the jekyll/github-metadata repository](https://github.com/jekyll/github-metadata/blob/a8a64bef6e1bd4b1f0b78fc10f18228d565b2972/lib/jekyll-github-metadata/ghp_metadata_generator.rb#L42-L44).

This data is filled in based on the output of `/repos/owner/repo/pages`, which returns a `cname` value. If that is missing or empty, then we build the site with url=http://username.github.io and baseurl=/project-name. This works very well when you're hosting directly from GitHub Pages.

Have you considered adding `blog.sentry.io` as a custom domain for your Pages repo? Then, the Pages site would set url=http://blog.sentry.io and baseurl=/ by default. That would be more in line with what you want (you would keep your https override in the configuration). You would receive warnings about the DNS not pointing to GitHub Pages, but those can be easily filtered by your mail client.

You are not the first person to file an issue for this (I saw one on jekyll/jekyll a few days ago), so perhaps the answer is to more strictly check `baseurl` being the default value.

**Comment by mattrobenolt** [comment] 2016-11-28 19:53
> Have you considered adding blog.sentry.io as a custom domain for your Pages repo? Then, the Pages site would set url=http://blog.sentry.io and baseurl=/ by default. That would be more in line with what you want (you would keep your https override in the configuration). You would receive warnings about the DNS not pointing to GitHub Pages, but those can be easily filtered by your mail client.

This is what we had, and exactly why we stopped since every committer to our blog repository got emailed and would ask, "did I break something?" :) So I explicitly removed the `CNAME` file and switched to this to mask it. So the only piece that doesn't work is how GH Pages is assigning the `baseurl` from my understanding.

**Comment by cameronmcefee** [comment] 2016-11-28 20:15
👍  Thanks for the clarification, @parkr. Feel free to close this since this is currently intended behavior.

FWIW: I'm guessing the intent of this is that things "just work". I'll admit we're definitely creating this edge case for ourselves. However, given that I've explicitly given it one value and get another—and the docs *recommend* this behavior—the switcheroo outcome feels weird.

**Comment by parkr** [comment] 2016-11-28 20:43
@cameronmcefee I agree, and the fact that an empty string is the default (instead of something like null) is part of the issue here. I think this will require that the default be changed to `null` in Jekyll and we overwrite it only when it's `null`.

**Comment by alias1** [comment] 2017-04-29 06:04
Running into this issue, had worked around it by using baseurl `/` but now that causes issues with `//` in other places.

Would it be possible to get a "never replace my baseurl even when it's empty" option that we could set in the config?

**Comment by benbalter** [comment] 2017-06-13 14:03
This is a duplicate of https://github.com/github/pages-gem/issues/350 and https://github.com/github/pages-gem/issues/419 and is being tracked in https://github.com/jekyll/github-metadata/pull/97.

**Closed by benbalter** 2017-06-13 14:03 UTC

**Comment by benbalter** [comment] 2017-07-18 21:22
This is now fixed. If you set your baseurl to `""` it will be respected.

**Comment by schifferl** [comment] 2017-07-20 16:18
@benbalter I think this might have caused unintended consequences. My `baseurl: ""` that had worked for a long time stopped being respected about two days ago. I went from [this](https://webcache.googleusercontent.com/search?q=cache:1vFW4gJeW6QJ:https://waldronlab.github.io/curatedMetagenomicData/+&cd=1&hl=en&ct=clnk&gl=us) to [this](https://waldronlab.github.io/curatedMetagenomicData/) with the change. The first URL is loaded from Google cache. My site repo is [here](https://github.com/waldronlab/curatedMetagenomicData/tree/master/docs). Going to hack a fix for the moment but I think the patch caused the issue.

**Comment by benbalter** [comment] 2017-07-20 16:47
@schifferl what do you want your baseurl to be? What did you have previously? What do you have now that works?

**Comment by schifferl** [comment] 2017-07-20 16:53
@benbalter, have a quick look at my site now https://waldronlab.github.io/curatedMetagenomicData/ this is with `baseurl: "/"`

I will change push a commit with `baseurl: ""` and watch what happens, all the links will break and javascript and css assets won't load.

Just if the patch had intended to "If you set your baseurl to "" it will be respected.", I think it may have done the opposite.

Thanks for having a look!

**Comment by benbalter** [comment] 2017-07-20 16:57
> Just if the patch had intended to "If you set your baseurl to "" it will be respected.", I think it may have done the opposite.

@schifferl if you set baseurl to "/", it should be treated as nil, meaning it will be overridden with what GitHub determines to be the baseurl, in your case `/curated/MetagenomicData'. If you set a baseurl of "" it will be respected, and links will likely try to load as `https://waldronlab.github.io/`.

**Comment by schifferl** [comment] 2017-07-20 19:55
Thank you for the clarification! I will switch over to `baseurl: "/"`

**Comment by benbalter** [comment] 2017-07-20 22:50
To clarify, and put another way, for our purposes, we're treating `""` as `nil`.

**Comment by juscuizon** [comment] 2017-07-26 02:53
Is there any fix for this? locally I cannot test with `baseurl: "/"`. Is there anyway to get back `baseurl:""` to work locally and on gh-pages? A couple of days ago it seemed fine.

**Comment by benbalter** [comment] 2017-07-26 13:38
@juscuizon I can't speak to the specifics of your local set up. If you [contact GitHub support](https://github.com/contact) they should be able to help you get things straightened out.
