### ISSUE TITLE
github pages build failure - Liquid Exception, Addressable::URI::InvalidURIError: Invalid scheme format

### ISSUE THREAD

**Issue by sbamin** [github/pages-gem#424] opened 2017-03-16 03:00 UTC
### Before submitting an issue, please be sure to

- [x] Read [the contributing instructions](https://github.com/github/pages-gem/blob/master/CONTRIBUTING.md#contributing-to-the-github-pages-gem)
- [x] Update to the latest Gem version (either `gem update github-pages` or `bundle update github-pages`)

### This issue affects

- [ ] The site generated by GitHub Pages
- [x] Building sites locally (only if using github-pages gem version 99 or lower)

### What did you do (e.g., steps to reproduce)

```
cd ~/scratch
git clone git@github.com:verhaaklab/verhaaklab.github.io.git
cd verhaaklab.github.io
bundle exec jekyll build --safe -t
```

* local build log for commit that failed to build on github: https://github.com/verhaaklab/verhaaklab.github.io/tree/d14cb93e76306ae34190b7be48df73935e003a0b

```
/Users/nova/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.2.1/lib/jekyll/hooks.rb:57: warning: constant ::Fixnum is deprecated
Configuration file: /Users/nova/scratch/verhaaklab.github.io/_config.yml
/Users/nova/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/jekyll-3.2.1/lib/jekyll/hooks.rb:57: warning: constant ::Fixnum is deprecated
            Source: /Users/nova/scratch/verhaaklab.github.io
       Destination: /Users/nova/scratch/verhaaklab.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
                    done in 3.93 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

That is, local build succeeds but github-pages fails. Travis CI passed too as it was following older github-pages v99 with addressable v2.3.8: Log file at https://s3.amazonaws.com/archive.travis-ci.org/jobs/211482114/log.txt

For local build, I used following Gemfile with older version of github-pages gem, v99 to match addressable v2.3.8 dependency. Errors seems to stem from using addressable v2.4.0 or higher. 
> addressable v2.4.0 is minimum required version for jekyll 3.4.1, which in turn is a minimum required version for github-pages gem v127

1. [Gemfile](https://github.com/verhaaklab/verhaaklab.github.io/blob/d14cb93e76306ae34190b7be48df73935e003a0b/Gemfile)
2. [Gemfile.lock](https://github.com/verhaaklab/verhaaklab.github.io/blob/d14cb93e76306ae34190b7be48df73935e003a0b/Gemfile.lock) following `bundle update`

### Steps to reproduce github side build log:

```
cd ~/scratch
git clone git@github.com:verhaaklab/verhaaklab.github.io.git
cd verhaaklab.github.io
rm Gemfile
rm Gemfile.lock
```

* Update Gemfile to use github-pages v127, as in https://gist.github.com/sbamin/055da7af68431c0332774edc4d8a3426

* Update bundle, `bundle update`, Gemfile.lock at https://gist.github.com/sbamin/055da7af68431c0332774edc4d8a3426

* build site

```
bundle exec jekyll build --safe -t
```

It fails with following error:

* local build --safe

```
nova@local:~/scratch/verhaaklab.github.io$ bundle exec jekyll build --safe
Configuration file: ~/scratch/verhaaklab.github.io/_config.yml
            Source: ~/scratch/verhaaklab.github.io
       Destination: ~/scratch/verhaaklab.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Invalid scheme format: Today, we report in journal Cancer Cell four distinct subtypes of GBM based on The Cancer Genome Atlas (TCGA) data on gene expression profile and clinical characteristics of patients with GBM. Publication in /_layouts/post.html
jekyll 3.4.1 | Error:  Invalid scheme format: Today, we report in journal Cancer Cell four distinct subtypes of GBM based on The Cancer Genome Atlas (TCGA) data on gene expression profile and clinical characteristics of patients with GBM. Publication
```

* debug

```
nova@local:~/scratch/verhaaklab.github.io$ bundle exec jekyll build --safe -t
Configuration file: ~/scratch/verhaaklab.github.io/_config.yml
            Source: ~/scratch/verhaaklab.github.io
       Destination: ~/scratch/verhaaklab.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: Invalid scheme format: Today, we report in journal Cancer Cell four distinct subtypes of GBM based on The Cancer Genome Atlas (TCGA) data on gene expression profile and clinical characteristics of patients with GBM. Publication in /_layouts/post.html
bundler: failed to load command: jekyll (/Users/nova/.rbenv/versions/2.4.0/bin/jekyll)
Addressable::URI::InvalidURIError: Invalid scheme format: Today, we report
```

>Detailed log at https://gist.github.com/sbamin/055da7af68431c0332774edc4d8a3426

### What did you expect to happen?

github-pages v127 is not building site because of apparent bug in addressable gem v2.4.0. Bug seems not to be present in addressable v2.3.8 but that required downgrading github-pages to v99, which allows jekyll to build site successfully.
 
### Additional information

* Source: https://github.com/verhaaklab/verhaaklab.github.io
* Failing commit on github side but building ok locally or at travis ci: https://github.com/verhaaklab/verhaaklab.github.io/tree/d14cb93e76306ae34190b7be48df73935e003a0b

**Comment by benbalter** [comment] 2017-03-16 14:03
Given that this Gem is intended "to help GitHub Pages users bootstrap and maintain a Jekyll build environment that most closely matches the GitHub pages build environment", we only support the latest version. If there's an upstream bug in addressable, I believe that would be the best place to address this issue.

**Comment by sbamin** [comment] 2017-03-16 19:03
just fyi, by addressable owner at https://github.com/sporkmonger/addressable/issues/234

>@sporkmonger: Good to know, but it's their bug, not Addressable's. I'm closing this as "Won't Fix", but might revisit for 3.0.

**Comment by sporkmonger** [comment] 2017-03-17 01:58
Hi Ben, this is not a bug in Addressable. You should not use Addressable to parse a git reference because a git reference is not always a URI. If it begins with e.g. `https`, sure Addressable is what you want, but for SSH references, those are actually in SCP format, which has never been standardized and it's not a URI. Addressable currently can only be used to parse legit URIs. I introduced a change that made parsing stricter and that's what "broke" things, but the actual bug was an incorrect assumption that an SCP reference was a URI. It is not.

There is no upstream bug in Addressable and no fix should be expected from upstream in the near term. I do plan to address this further in the future, but that isn't even medium term timeframe.

**Comment by benbalter** [comment] 2017-03-17 13:35
@sbamin Thanks for digging. Based on the error message, can you link to or paste the contents of the contents of the file that has the phrase "Today, we report in journal Cancer Cell four distinct subtypes of GBM based on The Cancer Genome Atlas (TCGA) data on gene expression profile and clinical characteristics of patients with GBM. Publication"? It seems Jekyll is passing that to Addressable to parse as a URL.

**Comment by sbamin** [comment] 2017-03-18 16:29
https://github.com/verhaaklab/verhaaklab.github.io/blob/master/_posts/2010-01-19-paper_gbm_subtypes_cancer_cell.md

Though the same error seems to appear for all other pages too (if I unpublish the above page and build site again). [post](https://github.com/verhaaklab/verhaaklab.github.io/blob/master/_layouts/post.html) and [base](https://github.com/verhaaklab/verhaaklab.github.io/blob/master/_layouts/base.html) look ok on quick look too.

**Comment by benbalter** [comment] 2017-03-20 13:48
@sbamin, @sporkmonger this is a bug with Jekyll core's implementation of the `uri_escape` filter. This should be tracked in https://github.com/jekyll/jekyll/issues/5954 and fixed in the next Jekyll release. In the mean time, you can skip the `uri_escape` filter or remove any colons from strings being passed to that filter (in this case the page title).

**Closed by benbalter** 2017-03-20 13:48 UTC
