### ISSUE TITLE
error when I'm trying for make a local host

### ISSUE THREAD

**Issue by STEdirisuriya** [github/pages-gem#508] opened 2017-12-11 18:13 UTC
When I try to make a local host from my windows pc. I typed "Jekyll Serve" on the cmd. But There ahow a file missing like following.
```
PS D:\My documents\GCI\gci17.fossasia.org> gem install github-pages
Fetching: kramdown-1.14.0.gem (100%)
Successfully installed kramdown-1.14.0
Fetching: listen-3.0.6.gem (100%)
Successfully installed listen-3.0.6
Fetching: jekyll-sass-converter-1.5.0.gem (100%)
Successfully installed jekyll-sass-converter-1.5.0
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing github-pages:
        ERROR: Failed to build gem native extension.

    current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
C:/tools/ruby24/bin/ruby.exe -r ./siteconf20171211-9464-34e8f8.rb extconf.rb
creating Makefile

current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1 for inspection.
Results logged to C:/tools/ruby24/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/commonmarker-0.17.7.1/gem_make.out
```
I installed bundle, Ruby, Chocaletry, Jekyll,... But why makes error?

**Comment by parkr** [comment] 2017-12-11 18:20
It looks like commonmarker's compilation can't find the `make` command. I don't use Windows, but a Google search shows me this: http://gnuwin32.sourceforge.net/packages/make.htm

/cc @kivikakk who might know more about this

**Comment by ashmaroli** [comment] 2017-12-12 02:06
You'll probably have to install both `make` and `cmake`
Ref: https://github.com/github/cmark#installing

**Comment by kivikakk** [comment] 2017-12-12 02:08
`cmake` is not a requirement of building `commonmarker` as of 0.17.7.1 (which is what the user was acquiring above); you will need the [Ruby DevKit](https://rubyinstaller.org/add-ons/devkit.html) installed on Windows, in order to provide `make`.

**Comment by kivikakk** [comment] 2017-12-12 02:08
(in other words, as long as you can install any native extension, you should be able to install this.)

**Comment by STEdirisuriya** [comment] 2017-12-12 18:34
@kivikakk how to install devkit

**Comment by kivikakk** [comment] 2017-12-12 20:24
@STEdirisuriya :wave: Please see the instructions here: https://rubyinstaller.org/add-ons/devkit.html Choose the option for your version of Ruby!

**Comment by STEdirisuriya** [comment] 2017-12-15 21:46
Not working

**Comment by kivikakk** [comment] 2017-12-17 22:25
You'll have to provide more information about what's happening; thanks!

**Comment by STEdirisuriya** [comment] 2017-12-18 21:03
Same error getting, what I have to add?

**Comment by kivikakk** [comment] 2017-12-20 02:01
I honestly don't know, I'm afraid. You might need to experiment to see why `make` isn't in the path/isn't being found by the Ruby native extension build process.

**Comment by kivikakk** [comment] 2017-12-20 20:50
Someone commented that https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows-8-1 worked for them; you might try seeing why `make` isn't on your PATH and/or moving it into your PATH like this.

**Comment by xNinjaKittyx** [comment] 2017-12-23 10:36
I have this problem too, so I went ahead and installed GNUmake and added it to my PATH.

Now I get the following error:

```
current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
C:/tools/ruby24/bin/ruby.exe -r ./siteconf20171223-8944-1pw6a5z.rb extconf.rb
creating Makefile

current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
make "DESTDIR=" clean

current directory: C:/tools/ruby24/lib/ruby/gems/2.4.0/gems/commonmarker-0.17.7.1/ext/commonmarker
make "DESTDIR="
generating commonmarker-x64-mingw32.def
make: *** No rule to make target `/C/tools/ruby24/include/ruby-2.4.0/ruby.h', needed by `arena.o'.  Stop.

make failed, exit code 2
```

**Comment by xNinjaKittyx** [comment] 2017-12-23 19:32
Ok, i see this issue#62, and I'll go ahead and reinstall ruby and see if that fixes it.

**Comment by parkr** [comment] 2018-01-02 20:41
Hope this is all fixed! All quiet for 10 days. This repo is for development of the GitHub Pages gem so I’m closing this issue as it’s not about development, but rather an installation issue of dependencies we don’t maintain in one specific environment case. Feel free to continue to conversation after the issue is closed!

**Closed by parkr** 2018-01-02 20:41 UTC
Labels: support

**Comment by vukienha** [comment] 2018-01-27 17:05
Dear all,
I got same issue when call "bundle install" in window.
I had tried to re-installed and go with option **3** at time install **MSYS2**.

![image](https://user-images.githubusercontent.com/21083487/35474279-907d472c-03be-11e8-802f-2c586f25819d.png)

And everything go fine.
![image](https://user-images.githubusercontent.com/21083487/35474295-c80ed372-03be-11e8-847e-766a80845266.png)

![image](https://user-images.githubusercontent.com/21083487/35474299-e3eb3806-03be-11e8-8407-926dc4778d59.png)

Good luck!
